config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :catagories
    resources :products do
      resources :stocks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end
  end
  devise_for :admins
    as :admin do
    get 'admins/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
    authenticate :admin_user do
        root "admin#index", as: :admin_root
    end    
    resources :catagories, only: [:show]
    resources :products, only: [:show] 
    get "admin" => "admin#index"
    get "cart" => "carts#show"
    post "checkout" => "checkouts#create"
end

app/models/catagory.rb
class Catagory < ApplicationRecord
  has_many :products
  has_one_attached :image
end

app/controllers/admin/catagories_controller.rb
class Admin::CatagoriesController < AdminController
  before_action :set_admin_catagory, only: %i[show edit update destroy]

  # GET /admin/catagories or /admin/catagories.json
  def index
    @admin_catagories = Catagory.all
  end

  # GET /admin/catagories/1 or /admin/catagories/1.json
  def show
  end

  # GET /admin/catagories/new
  def new
    @admin_catagory = Catagory.new
  end

  # GET /admin/catagories/1/edit
  def edit
  end

  # POST /admin/catagories or /admin/catagories.json
  def create
    @admin_catagory = Catagory.new(admin_catagory_params)

    respond_to do |format|
      if @admin_catagory.save
        format.html { redirect_to admin_catagory_url(@admin_catagory), notice: "Catagory was successfully created." }
        format.json { render :show, status: :created, location: @admin_catagory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_catagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/catagories/1 or /admin/catagories/1.json
  def update
    @admin_catagory = Catagory.find(params[:id])

    respond_to do |format|
      if @admin_catagory.update(admin_catagory_params)
        format.html { redirect_to admin_catagory_url(@admin_catagory), notice: "Catagory was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_catagory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_catagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/catagories/1 or /admin/catagories/1.json
  def destroy
    @admin_catagory.destroy!

    respond_to do |format|
      format.html { redirect_to admin_catagories_url, notice: "Catagory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin_catagory
    @admin_catagory = Catagory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def admin_catagory_params
    params.require(:catagory).permit(:name, :description, :image)
  end
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  def show 
    @catagory = Catagory.find(params[:id])
    @products = @catagory.products
  end
end 

app/helpers/admin/catagories_helper.rb
module Admin::CatagoriesHelper
end

app/views/admin/catagories/_catagory.html.erb
<div id="<%= dom_id catagory %>">
  <div class="flex flex-row justify-between">
    <div>
    <p class="my-5">
      <strong class="block font-medium mb-1">Name:</strong>
      <%= catagory.name %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= catagory.description %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Id:</strong>
      <%= catagory.id %>
    </p>
    </div>
    <%= image_tag catagory.image, class: "self-center justify-self-start w-60" %>
  </div>
  <% if action_name != "show" %>
    <%= link_to "Show this catagory", [:admin, catagory], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this catagory", edit_admin_catagory_path(:admin_catagory), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/catagories/_form.html.erb
<%= form_with(model: [:admin, admin_catagory], class: "contents") do |form| %>
  <% if admin_catagory.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(admin_catagory.errors.count, "error") %> prohibited this admin_catagory from being saved:</h2>

      <ul>
        <% admin_catagory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  
  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/catagories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Edit Category</h1>

  <%= render "form", admin_catagory: @admin_catagory %>

  <%= link_to "Show this catagory", [:admin, @admin_catagory], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to catagories", admin_catagories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/catagories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to "New category", new_admin_catagory_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="flex flex-col w-full">
    <div class="overlow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overlow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Name
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Description 
                </th>
              </tr>
            </thead>
            <tbody>
              <% @admin_catagories.each do |c| %>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 w-24 my">
                    <%= c.image.present? ? image_tag(c.image) : image_tag("https://via.placeholder.com/50") %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= link_to c.name, edit_admin_catagory_path(c) %> 
                    <%= c.id %>
                  </td>
                  <td class="text-teal px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= c.description %>
                  </td>
                  <%= puts c.inspect %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/catagories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New catagory</h1>

  <%= render "form", admin_catagory: @admin_catagory %>

  <%= link_to "Back to catagories", admin_catagories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/catagories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @admin_catagory %>

    <%= link_to "Edit this catagory", edit_admin_catagory_path(@admin_catagory), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Delete this catagory", admin_catagory_path(@admin_catagory), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to catagories", admin_catagories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>