config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    resources :catagories
    resources :products do
      resources :stocks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    end
  end
  devise_for :admins
    as :admin do
    get 'admins/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
    authenticate :admin_user do
        root "admin#index", as: :admin_root
    end    
    resources :catagories, only: [:show]
    resources :products, only: [:show] 
    get "admin" => "admin#index"
    get "cart" => "carts#show"
    post "checkout" => "checkouts#create"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/catagory.rb
class Catagory < ApplicationRecord
  has_many :products
  has_one_attached :image
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end

  belongs_to :catagory
  has_many :stocks
  has_many :order_products
end

app/models/product_stock.rb
class ProductStock < ApplicationRecord
  belongs_to :product
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!
  def index
    @orders = Order.where(fulfilled: false).order(created_at: :desc).take(5)
    @quick_stats = {
      sales: Order.where(created_at: Time.now.midnight..Time.now).count,
      revenue: Order.where(created_at: Time.now.midnight..Time.now).sum(:total)&.round(),
      avg_sale: Order.where(created_at: Time.now.midnight..Time.now).average(:total)&.round(),
      per_sale: OrderProduct.joins(:order).where(orders: { created_at: Time.now.midnight..Time.now })&.average(:quantity)
    }
    @orders_by_day = Order.where('created_at > ?', Time.now - 7.days).order(:created_at)
    @orders_by_day = @orders_by_day.group_by { |order| order.created_at.to_date }
    @revenue_by_day = @orders_by_day.map { |day, orders| [day.strftime("%A"), orders.sum(&:total)] }
    if @revenue_by_day.count < 7
      days_of_week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

      data_hash = @revenue_by_day.to_h
      current_day = Date.today.strftime("%A")
      current_day_index = days_of_week.index(current_day)
      next_day_index = (current_day_index + 1) % days_of_week.length

      ordered_days_with_current_last = days_of_week[next_day_index..-1] + days_of_week[0...next_day_index]
      complete_ordered_array_with_current_last = ordered_days_with_current_last.map { |day|
        [day, data_hash.fetch(day, 0)]
      }
      @revenue_by_day = complete_ordered_array_with_current_last
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    admin_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        
    end
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  def show 
    @catagory = Catagory.find(params[:id])
    @products = @catagory.products
  end
end 

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
    def create
        puts "create checkout"
    end    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @main_catagories = Catagory.take(6)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def show
        @product = Product.find(params[:id])
    end
end

app/helpers/admin/catagories_helper.rb
module Admin::CatagoriesHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/admin/index.html.erb
<div class="max-w-7xl mx-auto px-4 py-8">
  <!-- Daily Stats -->
  <div class="mb-12">
    <h2 class="text-3xl text-gray-800 font-semibold mb-4">Daily Stats</h2>
    <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
      <!-- Revenue -->
      <div class="bg-gradient-to-r from-indigo-500 to-indigo-700 p-6 rounded-lg text-white">
        <div class="font-bold text-lg mb-2">Revenue</div>
        <p class="text-xl">$<%= @quick_stats[:revenue] ? (@quick_stats[:revenue]/100.0).to_s : "0" %></p>
      </div>
      <!-- Total Sales -->
      <div class="bg-gradient-to-r from-indigo-500 to-indigo-700 p-6 rounded-lg text-white">
        <div class="font-bold text-lg mb-2">Total Sales</div>
        <p class="text-xl"><%= @quick_stats[:sales] ? @quick_stats[:sales].to_s : "0" %></p>
      </div>
      <!-- Average Sale -->
      <div class="bg-gradient-to-r from-indigo-500 to-indigo-700 p-6 rounded-lg text-white">
        <div class="font-bold text-lg mb-2">Average Sale</div>
        <p class="text-xl">$<%= @quick_stats[:avg_sale] ? (@quick_stats[:avg_sale]/100.0).to_s : "0" %></p>
      </div>
      <!-- Items/Sale -->
      <div class="bg-gradient-to-r from-indigo-500 to-indigo-700 p-6 rounded-lg text-white">
        <div class="font-bold text-lg mb-2">Items/Sale</div>
        <p class="text-xl"><%= @quick_stats[:per_sale].to_i %></p>
      </div>
    </div>
  </div>

  <!-- Revenue Chart -->
  <div class="mb-12">
    <h2 class="text-3xl text-gray-800 font-semibold mb-4">Revenue</h2>
    <div data-controller="dashboard" data-dashboard-revenue-value="<%= @revenue_by_day.to_json %>">
      <canvas id="revenueChart"></canvas>
    </div>
  </div>

  <!-- Recent Unfulfilled Orders -->
  <div>
    <h2 class="text-3xl text-gray-800 font-semibold mb-4">Recent Unfulfilled Orders</h2>
    <div class="overflow-x-auto">
      <table class="min-w-full bg-white rounded-lg shadow-md overflow-hidden">
        <thead class="bg-gray-200">
          <tr>
            <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-medium text-gray-500 uppercase">Order ID</th>
            <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-medium text-gray-500 uppercase">Customer</th>
            <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
            <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-xs font-medium text-gray-500 uppercase">Total Amount</th>
          </tr>
        </thead>
        <tbody class="text-gray-600">
          <% @orders.each do |order| %>
            <tr>
              <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-300"><%= link_to order.id, admin_order_path(order), class: "text-indigo-500 hover:underline" %></td>
              <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-300"><%= order.customer_email %></td>
              <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-300"><%= order.created_at.strftime("%B %d, %Y %H:%M") %></td>
              <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-300">$<%= (order.total/100.00).to_s %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application.tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex">
      <nav class="flex">
        <div class="bg-gray-500 w-64 p-4 h-screen sticky top-0">
            <div class="flex flex-col items-center justify-center text-center ">
                <%= image_tag "logo.png", class: "w-40 h-auto rounded drop-shadow-2xl" %>
                <h1 class="text-gray-200 text-3xl font-bold py-2 font-sans">چاند ٹیلر </h1>
                <h2 class="py-2 hidden md:block text-gray-200 text-xl"> Admin </h2>
            </div>
            <ul class="flex flex-col">
                <li>
                    <%= link_to admin_path, class: "block px-4 py-2 hover:rounded hover:bg-yellow-500 text-gray-200 hover:text-gray-800" do %>
                    <%= icon('fa-solid', 'desktop', class: 'mr-2') %> <span class="hidden md:inline-block">Dashboard</span>
                  <% end %>
                </li>
                <li>
                    <%= link_to admin_products_path, class: "block px-4 py-2 hover:bg-yellow-500 text-gray-200 hover:text-gray-800" do %>
                    <%= icon('fa-solid', 'cart-shopping', class: 'mr-2') %> <span class="hidden md:inline-block">Products</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_catagories_path, class: "block px-4 py-2 hover:bg-yellow-500 text-gray-200 hover:text-gray-800" do %>
                    <%= icon('fa-solid', 'list', class: 'mr-2') %> <span class="hidden md:inline-block">Categories</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_orders_path, class: "block px-4 py-2 hover:bg-yellow-500 text-gray-200 hover:text-gray-800" do %>
                    <%= icon('fa-solid', 'truck-fast', class: 'mr-2') %> <span class="hidden md:inline-block">Orders</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_admin_session_path, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out?" }, class: "block px-4 py-2 hover:bg-yellow-500 text-gray-200 hover:text-gray-800" do %>
                    <%= icon('fa-solid', 'sign-out', class: 'mr-2') %> <span class="hidden md:inline-block">Sign out</span>
                  <% end %>
                </li>
            </ul>
        </div>  
      </nav>
      <div class="w-full mt-4 p-8">
      <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application.tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script> 
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <main class="container mx-auto mt-28 max-w-7xl px-2 sm:px-6 lg:px-8">
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-gray-800 text-white">
  <div class="max-w-6xl mx-auto px-4 py-10 md:py-20">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
      <!-- About section -->
      <div class="space-y-8">
        <h3 class="text-sm font-semibold text-gray-200 uppercase tracking-wider">About Ecomm</h3>
        <p class="leading-6">
          Ecomm is a leading online marketplace, offering a wide range of products to cater to all your needs. Our commitment to quality and customer service ensures a great shopping experience.
        </p>
      </div>

      <!-- Quick Links -->
      <div class="mt-12 md:mt-0">
        <h3 class="text-sm font-semibold text-gray-200 uppercase tracking-wider">Quick Links</h3>
        <ul class="mt-4 space-y-4">
          <li>
            <%= link_to "Home", root_path, class: "text-base leading-6 text-white hover:text-gray-100" %>
          </li>
          <!-- Add more quick links as needed -->
        </ul>
      </div>

      <!-- Contact information -->
      <div class="mt-12 md:mt-0">
        <h3 class="text-sm font-semibold text-gray-200 uppercase tracking-wider">Contact</h3>
        <ul class="mt-4 space-y-4">
          <li>
            <p class="text-base leading-6 text-white">Raisham Street <br> Arifwala City, EC 12345</p>
          </li>
          <li>
            <p class="text-base leading-6 text-white">Email: support@ecom.com</p>
          </li>
          <li>
            <p class="text-base leading-6 text-white">Phone: (123) 456-7890</p>
          </li>
        </ul>
      </div>
    </div>

    <!-- Copyright -->
    <div class="border-t border-gray-700 mt-8 pt-8">
      <p class="text-base leading-6 text-gray-400 text-center">
        &copy; <%= Time.now.year %> Ecomm, Inc. All rights reserved.
      </p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="fixed top-0 w-full bg-gray-800 shadow-md z-10">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <!-- Logo -->
      <div class="flex-shrink-0">
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', class: 'h-10 lg:h-12 w-auto' %>
        <% end %>
      </div>

      <!-- Navigation links -->
      <div class="hidden sm:flex sm:items-center sm:ml-6">
        <div class="flex space-x-6">
          <%= link_to 'Shop', root_path, class: "text-white hover:text-gray-300 px-3 py-2 rounded-md text-sm font-medium" %>
          <%= link_to cart_path, class: "text-white hover:text-gray-300 px-3 py-2 rounded-md text-sm font-medium" do %>
            <%= icon 'fa-solid', 'shopping-cart' %>
          <% end %>
          <%= link_to "Admin", new_admin_session_path, class: "text-white hover:text-gray-300 px-3 py-2 rounded-md text-sm font-medium" %>
        </div>
      </div>

      <!-- Mobile menu button -->
      <div class="-mr-2 flex sm:hidden">
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:bg-gray-700 focus:text-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!-- Heroicon name: menu -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
          <!-- Heroicon name: menu-alt-1 -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1">
      <%= link_to 'Shop', root_path, class: "text-white hover:text-gray-300 block px-3 py-2 rounded-md text-base font-medium" %>
      <%= link_to cart_path, class: "text-white hover:text-gray-300 block px-3 py-2 rounded-md text-base font-medium" do %>
        <%= icon 'fa-solid', 'shopping-cart' %>
      <% end %>
      <%= link_to "Admin", new_admin_session_path, class: "text-white hover:text-gray-300 block px-3 py-2 rounded-md text-base font-medium" %>
    </div>
  </div>
</nav>